### ISSUE TITLE
cameraPreview is undefined

### ISSUE THREAD

**Issue by sangariv** [mbppower/CordovaCameraPreviewApp#14]
hi,
ince i build the app ,i get camerapreview is undefined inside app.startcamera function.
can u help me?

**Comment by andrislusis** [comment]
I am getting similar error:
Uncaught ReferenceError: CameraPreview is not defined

**Comment by erperejildo** [comment]
Just to check it, are you following these steps?:
1. Check if device is ready
2. Start camera
3. Show camera

If doesn't work try the third one with a callback in the second one.

**Comment by sunojvijayan** [comment]
I am also getting the same error is says www/cameraPreview.js not found when debugging in chrome

**Comment by sunojvijayan** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by Rakonda** [comment]
There is 2 resource erros

```
file:///android_asset/www/CameraPreview.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///android_asset/www/css/img/background.png Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Comment by Rakonda** [comment]
@sunojvijayan i mad a [pull](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview-sample-app/pull/16) with correction, i managed to make camera works.

**Comment by sunojvijayan** [comment]
Hi Rakonda

How can I get this. Do I have to uninstall and install again.

**Comment by sunojvijayan** [comment]
I have changed the code like you did in index file. 

CameraPreview.startCamera(); to 

cordova.plugins.camerapreview.startCamera({x: 0, y: 0});

but it still says CameraPreview is undefined.

**Comment by panlina** [comment]
@sunojvijayan maybe you should replace every `CameraPreview` to `cordova.plugins.camerapreview`

**Comment by veljkocasa** [comment]
Reinstall plugin using **--save** postfix.

> cordova plugin add `<plugin_name>` --save
> cordova clean
> cordova buid `<platform>`

**Comment by mstrop** [comment]
I have the same problem with Intel XDK environment build. In case I replace CameraPreview with cordova.plugins.camerapreview as panlina suggested I stop getting the error, but the preview doesn't work at all - nothing happens - no error and no camera picture on the screen. I event tried to have this sequence:

cordova.plugins.camerapreview.startCamera({x: 10, y: 10, width: 500, height:500, camera: "back", tapPhoto: true, previewDrag: true, toBack: false});
cordova.plugins.camerapreview.show();

**Comment by BernhardSmuts** [comment]
Hey Guys,

I see this point hasn't really been fixed...

For the life of me I can't get this example working, I see there are a few naming issues:
com.mbppower.camerapreview - plugin intalls to this name
cordova-plugin-camerapreview - this is the name used in the config.xml
plugins.cordova.io - This is the source of the plugin for the phonegap build

and the initial css doesn't point the the correct folder for the cat image...

Can anyone give me working code on this for a cordova phonegap CLI build?

Regards

**Comment by freshlySqueezedBananas** [comment]
Anyone with a solution? I lost 2 days trying to get this to work. Tried downgrading cordova version also, to no avail.

**Comment by Scriptonita** [comment]
It's work for my, but only with back camera. 

The front camera don't work, I don know if this can be for the same problem in official cordova camera plugin, where camera.CameraOptions.cameraDirection only work in default value.

https://www.npmjs.com/package/cordova-plugin-camera#android-quirks-1

**Comment by hardikaspire** [comment]
Hi, I have resolve this by placing the capture image code after start camera. Like this,    
```
cordova.plugins.camerapreview.startCamera(rect, "back", tapEnabled, dragEnabled, toBack);
//callback function for camera
cordova.plugins.camerapreview.setOnPictureTakenHandler(function(result) {}
```
