### ISSUE TITLE
Sample App May Be Missing Functionality or Broken after v0.9.0, PR's wanted!

### ISSUE THREAD

**Issue by westonganger** [mbppower/CordovaCameraPreviewApp#21]
This sample app was last updated for cordova-plugin-camera-preview v0.9.0. It needs to be fixed and updated from the latest master, probably in many ways.

Pull Requests are happily accepted! So if you find any bugs in this sample app, please fix them and create a PR as no one else is likely to fix it for you.

**Comment by NicksonYap** [comment]
Seems to build fine on `android@~7.1.4` 
and `8.1.2 (cordova-lib@8.1.1)`

**Comment by westonganger** [comment]
@NicksonYap not just build errors but it probably has bugs in general and is missing some of the features of the plugin.

**Comment by miktoki** [comment]
Is this intended to work in the browser?

**Comment by westonganger** [comment]
@miktoki no not in the browser, Android and iOS only.

**Comment by andreszs** [comment]
Hi, I took the liberty to edit the sample app and apply the styles from other [plugin demo apps](https://github.com/andreszs/cordova-plugin-demos) I've made. The PR #25 is waiting to be merged.

I've added missing methods, fixed others and updated the stylesheet to make it easier to test plugin functions. It has been tested for a few days now without issues.

### Methods overview

![image](https://user-images.githubusercontent.com/10298071/167954290-0a21ae79-f48c-4cec-aa5e-d86890b77667.png)


### Screenshots

![image](https://user-images.githubusercontent.com/10298071/167953234-0bd040d5-1819-4f1a-9e34-6d7327f0bbd9.png)

**Comment by westonganger** [comment]
This issue should be solved with #25. Thanks to @andreszs for his work on this
