### ISSUE TITLE
Error Intel XDK Compile

### ISSUE THREAD

**Issue by adanreyes18** [mbppower/CordovaCameraPreviewApp#3]
In the moment to compile show this error:
[javac] Compiling 14 source files to .../GopAppMx/platforms/android/ant-build/classes
    [javac] Note: .../GopAppMx/platforms/android/src/com/mbppower/CameraActivity.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

**Comment by diegolamonica** [comment]
I've solved changing code at row #107-#108 of `CameraActivity.java` from the original:

``` java
webView.getView().setBackgroundColor(0x00000000);
((ViewGroup)webView.getView()).bringToFront();
```

to

``` java
webView.setBackgroundColor(0x00000000);
webView.bringToFront();
```

Then XDK complies it smoothly
