### ISSUE TITLE
Camera disappears when toBack=true.

### ISSUE THREAD

**Issue by Ekta09** [mbppower/CordovaCameraPreviewApp#4]
In my application I am trying to implement the same code, Keeping **background as .png image having transparent background. Also setting background-color: transparent and toBack: true.**
In this case start camera button opens camera in hidden mode, pictures get captured but preview isn't visible. Please help me out, how to make preview visible ? 
Either Preview box gets invisible or It gets visible over the background (when toBack: false) 
**Note: I want background picture with transparent background(.png) over the Preview box, same as CordovaCameraPreview sample application.** I also made all other layers of my DevExtreme project css files as background-color: transparent. What am I missing out ?? 

Please help me out. Thanks in advance.

**Comment by mbppower** [comment]
Hi, did you put the style on the HTML body tag? That's the only requirement for this to work. Besides would be more easily to address your problem if you send me some screenshots of what you're getting with some code.

**Comment by Ekta09** [comment]
Yes I applied transparent style on body tag, but there are so many CSS which are getting applied in my application.
I opened my camera activity in new HTML page and overwrote all css classes which creates its background layer in my camera activity page. And it solved my problem.
Thank you so much for your response.
